name: Qc Preflight Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
 contents: read
 security-events: write

jobs:
  qcom-preflight-checks:
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@v2
    with:
        # ✅ Preflight Checkers
        enable-repolinter-check: true          # default: true
        enable-semgrep-scan: true              # default: true
        enable-copyright-license-check: false   # default: true
        enable-commit-email-check: true        # default: true
        enable-dependency-review: true         # default: true
        enable-armor-checkers: true
        armor-checker-options: '{"build-script":"ci/build.sh","runs-on":{"group":"GHA-SSG-Prd-SelfHosted-RG","labels":["self-hosted","ssg-prd-u2204-x64-large-od-ephem"]}}'
